services:
  - type: web
    name: checqin-booking
    runtime: ruby
    plan: free
    buildCommand: bundle install
    startCommand: bundle exec puma -C config/puma.rb
    autoDeploy: true
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_LOG_TO_STDOUT
        value: "true"
      - key: RAILS_SERVE_STATIC_FILES
        value: "true"
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: checqin-db
          property: connectionString
      - key: APP_HOST
        value: checqin-booking.onrender.com
      - key: OTP_SECRET_KEY
        value: doxjZlFC5bbP2qCV3cPcXHO3c77bRm

databases:
  - name: checqin-db
    plan: free
    databaseName: checqin_production
